import type { ProductOffer } from './types'

// UI検証用のサンプルデータ。実データ(products.json)が読めない場合のフォールバック専用。
const officialUrl = 'https://example.com/'
const checkedAt = '2026-06-24'

type StaticOffer = Omit<
  ProductOffer,
  'fetchStatus' | 'lastSuccessfulPriceYen' | 'lastSuccessfulCheckedAt' | 'couponSource' | 'priceEvidence' | 'sourceType' | 'detectedSizeGrams' | 'detectedFlavor' | 'detectedSku' | 'previousEffectivePriceYen' | 'priceDiffYen' | 'freeShippingMinYen' | 'regularEffectivePriceYen' | 'regularPricePer3KgYen'
>

function withStaticDefaults(offer: StaticOffer): ProductOffer {
  return {
    ...offer,
    freeShippingMinYen: null,
    regularEffectivePriceYen: offer.regularPriceYen,
    regularPricePer3KgYen: offer.regularPriceYen === null ? null : Math.round(offer.regularPriceYen / (offer.sizeGrams / 1000) * 3),
    fetchStatus: 'success',
    lastSuccessfulPriceYen: offer.effectivePriceYen,
    lastSuccessfulCheckedAt: offer.lastCheckedAt,
    couponSource: offer.hasCoupon ? 'manual' : 'none',
    priceEvidence: 'static sample data',
    detectedSizeGrams: offer.expectedSizeGrams ?? offer.sizeGrams,
    detectedFlavor: offer.expectedFlavor ?? null,
    detectedSku: offer.expectedSku ?? null,
    previousEffectivePriceYen: null,
    priceDiffYen: null,
    sourceType: 'manual',
  }
}

export const sampleOffers: ProductOffer[] = [
  withStaticDefaults({
    productId: 'myprotein-impact-wpc-25kg',
    offerId: 'myprotein-impact-wpc-25kg-official',
    maker: 'Myprotein',
    name: 'Impact ホエイ プロテイン 2.5kg',
    proteinType: 'WPC',
    sizeGrams: 2500,
    imageUrl: './images/wpc.svg',
    storeName: 'Myprotein 公式ストア',
    storeType: 'official',
    productUrl: officialUrl,
    regularPriceYen: 11990,
    salePriceYen: 6890,
    couponDiscountYen: 1000,
    shippingYen: 0,
    effectivePriceYen: 5890,
    pricePerKgYen: 2356,
    pricePer3KgYen: 7068,
    hasSale: true,
    hasCoupon: true,
    couponLabel: 'コード適用',
    saleLabel: '大型SALE',
    discountRate: 51,
    inStock: true,
    lastCheckedAt: checkedAt,
  }),
  withStaticDefaults({
    productId: 'xplosion-wpc-3kg',
    offerId: 'xplosion-wpc-3kg-official',
    maker: 'X-PLOSION',
    name: 'ホエイプロテイン ベーシック 3kg',
    proteinType: 'WPC',
    sizeGrams: 3000,
    imageUrl: './images/wpc.svg',
    storeName: 'X-PLOSION 公式ストア',
    storeType: 'official',
    productUrl: officialUrl,
    regularPriceYen: 7990,
    salePriceYen: 7280,
    couponDiscountYen: 500,
    shippingYen: 0,
    effectivePriceYen: 6780,
    pricePerKgYen: 2260,
    pricePer3KgYen: 6780,
    hasSale: true,
    hasCoupon: true,
    couponLabel: '公式クーポン',
    saleLabel: '週末SALE',
    discountRate: 15,
    inStock: true,
    lastCheckedAt: checkedAt,
  }),
  withStaticDefaults({
    productId: 'valx-wpc-3kg',
    offerId: 'valx-wpc-3kg-official',
    maker: 'VALX',
    name: 'ホエイプロテイン ベーシック 3kg',
    proteinType: 'WPC',
    sizeGrams: 3000,
    imageUrl: './images/wpc.svg',
    storeName: 'VALX 公式ストア',
    storeType: 'official',
    productUrl: officialUrl,
    regularPriceYen: 10480,
    salePriceYen: 9480,
    couponDiscountYen: 500,
    shippingYen: 0,
    effectivePriceYen: 8980,
    pricePerKgYen: 2993,
    pricePer3KgYen: 8980,
    hasSale: true,
    hasCoupon: true,
    couponLabel: '500円OFF',
    saleLabel: null,
    discountRate: 14,
    inStock: true,
    lastCheckedAt: checkedAt,
  }),
  withStaticDefaults({
    productId: 'myprotein-impact-wpi-25kg',
    offerId: 'myprotein-impact-wpi-25kg-official',
    maker: 'Myprotein',
    name: 'Impact ホエイ アイソレート 2.5kg',
    proteinType: 'WPI',
    sizeGrams: 2500,
    imageUrl: './images/wpi.svg',
    storeName: 'Myprotein 公式ストア',
    storeType: 'official',
    productUrl: officialUrl,
    regularPriceYen: 16990,
    salePriceYen: 9990,
    couponDiscountYen: 1500,
    shippingYen: 0,
    effectivePriceYen: 8490,
    pricePerKgYen: 3396,
    pricePer3KgYen: 10188,
    hasSale: true,
    hasCoupon: true,
    couponLabel: 'コード適用',
    saleLabel: '50%OFF相当',
    discountRate: 50,
    inStock: true,
    lastCheckedAt: checkedAt,
  }),
  withStaticDefaults({
    productId: 'xplosion-wpi-3kg',
    offerId: 'xplosion-wpi-3kg-official',
    maker: 'X-PLOSION',
    name: 'WPI ホエイプロテイン 3kg',
    proteinType: 'WPI',
    sizeGrams: 3000,
    imageUrl: './images/wpi.svg',
    storeName: 'X-PLOSION 公式ストア',
    storeType: 'official',
    productUrl: officialUrl,
    regularPriceYen: 10980,
    salePriceYen: 9980,
    couponDiscountYen: 0,
    shippingYen: 0,
    effectivePriceYen: 9980,
    pricePerKgYen: 3327,
    pricePer3KgYen: 9980,
    hasSale: true,
    hasCoupon: false,
    couponLabel: null,
    saleLabel: 'SALE',
    discountRate: 9,
    inStock: true,
    lastCheckedAt: checkedAt,
  }),
  withStaticDefaults({
    productId: 'valx-wpi-3kg',
    offerId: 'valx-wpi-3kg-official',
    maker: 'VALX',
    name: 'WPI パーフェクト 3kg',
    proteinType: 'WPI',
    sizeGrams: 3000,
    imageUrl: './images/wpi.svg',
    storeName: 'VALX 公式ストア',
    storeType: 'official',
    productUrl: officialUrl,
    regularPriceYen: 15480,
    salePriceYen: 14280,
    couponDiscountYen: 1000,
    shippingYen: 0,
    effectivePriceYen: 13280,
    pricePerKgYen: 4427,
    pricePer3KgYen: 13280,
    hasSale: true,
    hasCoupon: true,
    couponLabel: '期間限定クーポン',
    saleLabel: null,
    discountRate: 14,
    inStock: true,
    lastCheckedAt: checkedAt,
  }),
  withStaticDefaults({
    productId: 'myprotein-soy-25kg',
    offerId: 'myprotein-soy-25kg-official',
    maker: 'Myprotein',
    name: 'ソイ プロテイン アイソレート 2.5kg',
    proteinType: 'SOY',
    sizeGrams: 2500,
    imageUrl: './images/soy.svg',
    storeName: 'Myprotein 公式ストア',
    storeType: 'official',
    productUrl: officialUrl,
    regularPriceYen: 9990,
    salePriceYen: 5990,
    couponDiscountYen: 800,
    shippingYen: 0,
    effectivePriceYen: 5190,
    pricePerKgYen: 2076,
    pricePer3KgYen: 6228,
    hasSale: true,
    hasCoupon: true,
    couponLabel: 'コード適用',
    saleLabel: 'SALE',
    discountRate: 48,
    inStock: true,
    lastCheckedAt: checkedAt,
  }),
  withStaticDefaults({
    productId: 'xplosion-soy-3kg',
    offerId: 'xplosion-soy-3kg-official',
    maker: 'X-PLOSION',
    name: '100% ソイプロテイン 3kg',
    proteinType: 'SOY',
    sizeGrams: 3000,
    imageUrl: './images/soy.svg',
    storeName: 'X-PLOSION 公式ストア',
    storeType: 'official',
    productUrl: officialUrl,
    regularPriceYen: 7490,
    salePriceYen: 6880,
    couponDiscountYen: 400,
    shippingYen: 0,
    effectivePriceYen: 6480,
    pricePerKgYen: 2160,
    pricePer3KgYen: 6480,
    hasSale: true,
    hasCoupon: true,
    couponLabel: 'キャンペーン',
    saleLabel: 'SALE',
    discountRate: 13,
    inStock: true,
    lastCheckedAt: checkedAt,
  }),
  withStaticDefaults({
    productId: 'valx-soy-1kg',
    offerId: 'valx-soy-1kg-official',
    maker: 'VALX',
    name: 'ソイプロテイン 1kg',
    proteinType: 'SOY',
    sizeGrams: 1000,
    imageUrl: './images/soy.svg',
    storeName: 'VALX 公式ストア',
    storeType: 'official',
    productUrl: officialUrl,
    regularPriceYen: 4280,
    salePriceYen: null,
    couponDiscountYen: 0,
    shippingYen: 0,
    effectivePriceYen: 4280,
    pricePerKgYen: 4280,
    pricePer3KgYen: 12840,
    hasSale: false,
    hasCoupon: false,
    couponLabel: null,
    saleLabel: null,
    discountRate: 0,
    inStock: true,
    lastCheckedAt: checkedAt,
  }),
]
